apiVersion: apps/v1
kind: Deployment
metadata:
  name: user03-jitpakorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user03-jitpakorn
  template:
    metadata:
      labels:
        app: user03-jitpakorn
    spec:
      containers:
        - name: user03-jitpakorn
          image: ghcr.io/jitpakornr/web
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user03-jitpakorn
  labels:
    app: user03-jitpakorn
spec:
  selector:
    app: user03-jitpakorn
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
#selectort app: ต้องเหมือนกัน
